[package]
name = "owsql"
version = "0.1.0"
authors = ["kmgy <bhnk1270223@gn.iwasaki.ac.jp>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[features]
sqlite = ["libsqlite3-sys"]


[dependencies]
libsqlite3-sys = { version = "0.18", optional = true }
