
name: CI

on:
  push:
    branches:
        - main
        - develop
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test

    strategy:
      fail-fast: false

      matrix:
        platform:
          - { target: x86_64-pc-windows-msvc, os: windows-latest }
          - { target: x86_64-unknown-linux-gnu, os: ubuntu-latest }
          - { target: x86_64-apple-darwin, os: macos-latest }
          - { target: x86_64-pc-windows-gnu, os: windows-latest, host: -x86_64-pc-windows-gnu }

    runs-on: ${{ matrix.platform.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Build sqlite
        run: cargo build --features sqlite --all-targets

      - name: Run tests sqlite
        run: cargo test --features sqlite --all-targets

      - name: Document tests sqlite
        run: cargo test --features sqlite --doc

  clippy:
    name: Clippy

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: prepare
        run: |
          rustup component add clippy
          echo "clippy_flags=-W clippy::dbg_macro -A clippy::uninlined_format_args -A deprecated" >> $GITHUB_ENV

      - name: clippy sqlite
        run: cargo clippy --all-targets --features sqlite -- ${{ env.clippy_flags }}

      - name: clippy mysql
        run: cargo clippy --all-targets --features mysql -- ${{ env.clippy_flags }}

      - name: clippy postgres
        run: cargo clippy --all-targets --features postgres -- ${{ env.clippy_flags }}

      - name: clippy all features
        run: cargo clippy --all-targets --all-features -- ${{ env.clippy_flags }}

