
name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test

    strategy:
      fail-fast: false

      matrix:
        platform:
          - { target: x86_64-pc-windows-msvc, os: windows-latest }
          - { target: x86_64-unknown-linux-gnu, os: ubuntu-latest }
          - { target: x86_64-apple-darwin, os: macos-latest }
          - { target: x86_64-pc-windows-gnu, os: windows-latest, host: -x86_64-pc-windows-gnu }

    runs-on: ${{ matrix.platform.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: cargo build --all-features --all-targets

      - name: Run tests
        run: cargo test --all-features --all-targets

      - name: Document tests
        run: cargo test --all-features --doc

  clippy:
    name: Clippy

    strategy:
      fail-fast: false

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: prepare
        run: rustup component add clippy

      - name: clippy
        run: cargo clippy --all-targets --all-features -- -D clippy::dbg_macro -D warnings

